alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: app-fd7a6745-1711-44c1-b86e-3cbd8b3d0412
  db_name: kirimku
  engine: PG
  name: kirimku
  production: true
  version: "14"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: kirimku-kirimku-backend
    match:
      path:
        prefix: /
name: kirimku-backend
region: sgp
domains:
- domain: api.kirimku.com
  type: PRIMARY
  wildcard: false
  zone: kirimku.com
services:
- envs:
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"
  - key: APP_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: APP_VERSION
    scope: RUN_AND_BUILD_TIME
    value: "1.1.0"
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${kirimku.DATABASE_URL}
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${kirimku.HOSTNAME}
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${kirimku.PORT}
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
    value: ${kirimku.USERNAME}
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${kirimku.PASSWORD}
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: ${kirimku.DATABASE}
  - key: DB_SSL_MODE
    scope: RUN_AND_BUILD_TIME
    value: require
  - key: DB_MAX_OPEN_CONNS
    scope: RUN_AND_BUILD_TIME
    value: "15"
  - key: DB_MAX_IDLE_CONNS
    scope: RUN_AND_BUILD_TIME
    value: "5"
  - key: DB_CONN_MAX_LIFETIME
    scope: RUN_AND_BUILD_TIME
    value: "300"
  - key: DB_HEALTH_CHECK_PERIOD
    scope: RUN_AND_BUILD_TIME
    value: "30"
  - key: SESSION_KEY
    scope: RUN_AND_BUILD_TIME
    value: "c5cd82bf5389c7e3bf0ca8ff5b4823d032b428c89446cbe8b2c3791dc2727a38"
  - key: SESSION_MAX_AGE
    scope: RUN_AND_BUILD_TIME
    value: "86400"
  - key: SESSION_SECURE
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: SESSION_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: ""
  - key: SESSION_SAME_SITE
    scope: RUN_AND_BUILD_TIME
    value: lax
  - key: LOG_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: info
  - key: LOG_FILE
    scope: RUN_AND_BUILD_TIME
    value: app.log
  - key: LOG_FORMAT
    scope: RUN_AND_BUILD_TIME
    value: json
  - key: BASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}
  - key: FRONTEND_URL
    scope: RUN_AND_BUILD_TIME
    value: https://kirimku.com
  - key: ALLOWED_ORIGINS
    scope: RUN_AND_BUILD_TIME
    value: https://kirimku.com
  - key: RATE_LIMIT_PER_SECOND
    scope: RUN_AND_BUILD_TIME
    value: "5.0"
  - key: RATE_LIMIT_TTL
    scope: RUN_AND_BUILD_TIME
    value: "1h"
  - key: GOOGLE_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    value: ${GOOGLE_CLIENT_ID}
  - key: GOOGLE_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: ${GOOGLE_CLIENT_SECRET}
  - key: GOOGLE_REDIRECT_URL
    scope: RUN_AND_BUILD_TIME
    value: https://kirimku.com/auth/callback
  - key: SMTP_HOST
    scope: RUN_AND_BUILD_TIME
    value: smtp.office365.com
  - key: SMTP_PORT
    scope: RUN_AND_BUILD_TIME
    value: "587"
  - key: SMTP_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: support@kirimku.com
  - key: SMTP_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${SMTP_PASSWORD}
  - key: SMTP_FROM_NAME
    scope: RUN_AND_BUILD_TIME
    value: Tim Kirimku
  - key: SMTP_FROM_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: noreply@kirimku.com
  - key: MAILGUN_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: kirimku.com
  - key: PAYMENT_GATEWAY
    scope: RUN_AND_BUILD_TIME
    value: durianpay
  - key: PAYMENT_CALLBACK_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_URL}/api/v1/invoices/callback
  - key: PAYMENT_SUCCESS_REDIRECT_URL
    scope: RUN_AND_BUILD_TIME
    value: https://your-frontend-domain.com/payment/success
  - key: PAYMENT_FAILURE_REDIRECT_URL
    scope: RUN_AND_BUILD_TIME
    value: https://your-frontend-domain.com/payment/failed
  - key: XENDIT_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${XENDIT_API_KEY}
  - key: XENDIT_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${XENDIT_SECRET_KEY}
  - key: XENDIT_CALLBACK_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: ${XENDIT_CALLBACK_TOKEN}
  - key: XENDIT_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: XENDIT_FEE_CALCULATION
    scope: RUN_AND_BUILD_TIME
    value: exclude
  - key: XENDIT_PAYMENT_METHODS
    scope: RUN_AND_BUILD_TIME
    value: SHOPEEPAY,DANA,OVO,LINKAJA
  - key: XENDIT_INVOICE_EXPIRY
    scope: RUN_AND_BUILD_TIME
    value: "86400"
  - key: JNE_API_URL
    scope: RUN_AND_BUILD_TIME
    value: https://api.jne.co.id
  - key: JNE_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: ${JNE_USERNAME}
  - key: JNE_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: ${JNE_API_KEY}

  # Sicepat KEY
  - key: SICEPAT_API_URL
    scope: RUN_AND_BUILD_TIME
    value: https://api.sicepat.com
  - key: SICEPAT_PICKUP_URL
    scope: RUN_AND_BUILD_TIME
    value: https://pickup.sicepat.com
  - key: SICEPAT_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: C8F0CCE890476AD71EBE2946BCE4488D
  - key: SICEPAT_API_TRACKING_KEY
    scope: RUN_AND_BUILD_TIME
    value: dd2268014c90c7737f7bdf508a73aba4
  # SiCepat Resi Number Configuration
  - key: SICEPAT_RESI_RANGE_START
    scope: RUN_AND_BUILD_TIME
    value: "999001200000"
  - key: SICEPAT_RESI_RANGE_END
    scope: RUN_AND_BUILD_TIME
    value: "999001209999"
  - key: CONFIG_DIR
    scope: RUN_AND_BUILD_TIME
    value: /app/internal/config
  # Test Admin Credentials (for testing admin endpoints)
  - key: TEST_ADMIN_EMAIL
    scope: RUN_AND_BUILD_TIME
    value: ${TEST_ADMIN_EMAIL}
  - key: TEST_ADMIN_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${TEST_ADMIN_PASSWORD}
  - key: TEST_ADMIN_NAME
    scope: RUN_AND_BUILD_TIME
    value: ${TEST_ADMIN_NAME}
  - key: TEST_ADMIN_PHONE
    scope: RUN_AND_BUILD_TIME
    value: ${TEST_ADMIN_PHONE}
  # Grafana Cloud / Observability Configuration
  - key: LOKI_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://logs-prod-020.grafana.net/loki/api/v1/push"
  - key: LOKI_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: "1265576"
  - key: LOKI_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: "${GRAFANA_LOKI_PASSWORD}"
  - key: LOKI_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: LOKI_BATCH_SIZE
    scope: RUN_AND_BUILD_TIME
    value: "100"
  - key: LOKI_BATCH_WAIT
    scope: RUN_AND_BUILD_TIME
    value: "1s"
  - key: LOKI_LABELS
    scope: RUN_AND_BUILD_TIME
    value: service=kirimku-backend,environment=production
  # Prometheus metrics
  - key: METRICS_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: METRICS_NAMESPACE
    scope: RUN_AND_BUILD_TIME
    value: kirimku
  - key: METRICS_SUBSYSTEM
    scope: RUN_AND_BUILD_TIME
    value: backend
  - key: METRICS_ALLOW_PUBLIC
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: METRICS_ALLOWED_IPS
    scope: RUN_AND_BUILD_TIME
    value: ${METRICS_ALLOWED_IPS}
  # JNE Additional Configuration
  - key: JNE_CUSTOMER_ID
    scope: RUN_AND_BUILD_TIME
    value: ${JNE_CUSTOMER_ID}
  - key: JNE_SKIP_REGISTER
    scope: RUN_AND_BUILD_TIME
    value: "false"
  # JNT Additional Configuration
  - key: JNT_API_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://api.jnt.co.id"
  - key: JNT_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: "AKe62df84bJ3d8e4b1hea2R45j11klsb"
  - key: JNT_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: "KIRIMKU"
  - key: JNT_API_KEY_NAME
    scope: RUN_AND_BUILD_TIME
    value: "UJM73Y"
  - key: JNT_ORDER_API_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://ecommerce.jntexpress.id/jts-idn-ecommerce-api/api/order/create"
  - key: JNT_TARIFF_API_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://partner-track.jet.co.id"
  - key: JNT_TARIFF_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: "5rgOUX4dDSJl"
  - key: JNT_TRACKING_API_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://secure-jk.jet.co.id/jandt-order-web/track/trackAction!tracking.action"
  
  # ELK Stack Configuration
  - key: ELASTIC_HOSTS
    scope: RUN_AND_BUILD_TIME
    value: ${ELASTIC_HOSTS}
  - key: ELASTIC_USERNAME
    scope: RUN_AND_BUILD_TIME
    value: ${ELASTIC_USERNAME}
  - key: ELASTIC_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${ELASTIC_PASSWORD}
  - key: LOGSTASH_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${LOGSTASH_HOST}
  - key: KIBANA_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${KIBANA_HOST}
  # Mailgun API Key
  - key: MAILGUN_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: "${MAILGUN_API_KEY}"
  # Xendit Base URL
  - key: XENDIT_BASE_URL
    scope: RUN_AND_BUILD_TIME
    value: https://api.xendit.co
  # DurianPay Configuration
  - key: DURIANPAY_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: "dp_live_KIkfLOpdo0saxt3H"
  - key: DURIANPAY_BASE_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://api.durianpay.id"
  - key: DURIANPAY_CALLBACK_URL
    scope: RUN_AND_BUILD_TIME
    value: "https://api.kirimku.com/api/v1/webhooks/payments/durianpay"
  - key: DURIANPAY_WEBHOOK_SECRET
    scope: RUN_AND_BUILD_TIME
    value: ${DURIANPAY_WEBHOOK_SECRET}
  - key: DURIANPAY_PUBLIC_KEY_PATH
    scope: RUN_AND_BUILD_TIME
    value: keys/durianpay_public_key_durianpay.pem
  - key: DURIANPAY_ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: DURIANPAY_REQUEST_TIMEOUT
    scope: RUN_AND_BUILD_TIME
    value: "30"
  - key: DURIANPAY_SNAP_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: DURIANPAY_SNAP_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    value: ${DURIANPAY_SNAP_CLIENT_ID}
  - key: DURIANPAY_SNAP_PRIVATE_KEY_ID
    scope: RUN_AND_BUILD_TIME
    value: ${DURIANPAY_SNAP_PRIVATE_KEY_ID}
  # Payment Common Settings
  - key: INVOICE_EXPIRY_HOURS
    scope: RUN_AND_BUILD_TIME
    value: "24"
  - key: DEFAULT_EWALLET_CHANNEL
    scope: RUN_AND_BUILD_TIME
    value: SHOPEEPAY
  # SAPX API Configuration
  - key: SAPX_API_KEY_PICKUP
    scope: RUN_AND_BUILD_TIME
    value: 58d703afc44a92285bf12fc77d0e92f673f88e3b
  - key: SAPX_API_KEY_DROPOFF
    scope: RUN_AND_BUILD_TIME
    value: 58d703afc44a92285bf12fc77d0e92f673f88e3b
  - key: SAPX_API_URL
    scope: RUN_AND_BUILD_TIME
    value: https://api.coresyssap.com
  - key: SAPX_API_TRACKER_URL
    scope: RUN_AND_BUILD_TIME
    value: https://track.coresyssap.com
  - key: SAPX_CUSTOMER_CODE_NON_COD
    scope: RUN_AND_BUILD_TIME
    value: CGK128854
  - key: SAPX_CUSTOMER_CODE_COD
    scope: RUN_AND_BUILD_TIME
    value: CGK128853
  - key: SAPX_MAX_RETRIES
    scope: RUN_AND_BUILD_TIME
    value: "3"
  # Telegram Alerting Configuration
  - key: TELEGRAM_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: TELEGRAM_BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: "8499486288:AAFfl0t5znW-xsmtDBjHNaUK9qRVuzH6Dj4"
  - key: TELEGRAM_CHAT_IDS
    scope: RUN_AND_BUILD_TIME
    value: "-4827760770"
  - key: TELEGRAM_ALERT_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: "error"
  - key: TELEGRAM_TIMEOUT
    scope: RUN_AND_BUILD_TIME
    value: "10s"
  - key: TELEGRAM_REFUND_ENABLED
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: TELEGRAM_REFUND_BOT_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: "8406226398:AAFseTZ9-a_2kG3NH9QrheWwnfxLnzaP6OY"
  - key: TELEGRAM_REFUND_CHAT_IDS
    scope: RUN_AND_BUILD_TIME
    value: "-4884792820"
  - key: TELEGRAM_REFUND_ALERT_LEVEL
    scope: RUN_AND_BUILD_TIME
    value: "info"
  - key: TELEGRAM_REFUND_TIMEOUT
    scope: RUN_AND_BUILD_TIME
    value: "30s"

  health_check:
    failure_threshold: 3
    http_path: /api/v1/health
    initial_delay_seconds: 30
    period_seconds: 10
    success_threshold: 1
    timeout_seconds: 5
  http_port: 8080
  image:
    registry: ghcr.io
    registry_credentials: kirimku:${GITHUB_TOKEN}
    registry_type: GHCR
    repository: kirimku/kirimku-backend
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xs
  name: kirimku-kirimku-backend
