CGK10000:
  - Jakarta Barat
  - Jakarta Pusat
  - Jakarta Selatan
  - Jakarta Timur
  - Jakarta Utara
  - Kepulauan Seribu
BOO10000:
  - Bogor
  - Kab. Bogor
SOC10000:
  - Solo
SDA10000: 
  - Sidoarjo
PBL10000:
  - Lumajang
  - Probolinggo
  - Kab. Probolinggo
  - Situbondo
MES21100:
  - Tebing Tinggi
TSM20000:
  - Banjar
SOC20500:
  - Sukoharjo
BDO20700:
  - Garut
TKG20906:
  - Lampung Tengah
  - Lampung Timur
BTJ20500:
  - Aceh Tengah
BTJ20300:
  - Aceh Barat
BTJ10200:
  - Lhokseumawe
  - Aceh Besar
